### ISSUE TITLE
How to encrypt public keys?

### ISSUE THREAD

**Issue by vrgenl** [SocialGouv/webseal#36]
I've tried encrypting my public key

```
MY_PUBLIC_KEY=-----BEGIN CERTIFICATE-----
sdfkjsdgfhdgf
-----END CERTIFICATE-----
```

and

```
MY_PUBLIC_KEY="-----BEGIN CERTIFICATE-----
sdfkjsdgfhdgf
-----END CERTIFICATE-----"
```

Without luck, any pointer on how to encrypt this?

**Comment by revolunet** [comment]
Hello, i think this version doesnt handle multiline correcltly yet.
someone has to backport these changes :

 - https://github.com/SocialGouv/sre-tools/pull/131
 - https://github.com/SocialGouv/sre-tools/pull/133

**Comment by vrgenl** [comment]
Thanks for your reply, ended up base64 the output and decrypting the base64 in my application.

Worked fine 👍
